name: Validation
description: Check and validate metagraf.json with conftest

runs:
  using: composite
  steps:
    - name: setup conftest
      uses: terbolous/action-setup-conftest@main
    - name: run conftest
      shell: bash
      run: conftest test -p "${{ github.action_path }}/policy/ini.rego" config.ini
      